In [2]:
from __future__ import print_function, division


from keras.datasets import mnist
from keras.layers import Input, Dense, Reshape, Flatten, Dropout
from keras.layers import BatchNormalization, Activation, ZeroPadding2D
from keras.layers.advanced_activations import LeakyReLU
from keras.layers.convolutional import UpSampling2D, Conv2D
from keras.models import Sequential, Model
from keras.optimizers import Adam
from keras.preprocessing import sequence

import tensorflow as tf

import matplotlib.pyplot as plt

import sys

import numpy as np



In [7]:
data = np.load("mnist_test_seq.npy")
cframe1 = data[0:3]
cframe2 = data[3:6] 
cframe3 = data[6:9]
cframe4 = data[9:12]
cframe5 = data[12:15]
cframe6 = data[15:18]
cframes = np.concatenate((cframe1,cframe2,cframe3,cframe4,cframe5,cframe6),axis=1).transpose(1,2,3,0)
Y_train = cframes

# Rescale -1 to 1
Y_train = Y_train / 127.5 - 1.
Y_train = np.expand_dims(Y_train, axis=0)
Y_train.shape

Y_train.shape, Y_train[0].shape, Y_train[0][0,:,:,0].shape

((1, 60000, 64, 64, 3), (60000, 64, 64, 3), (64, 64))

In [8]:
(X_train, _), (_, _) = mnist.load_data()
print(X_train.shape)
# Rescale -1 to 1
X_train = X_train / 127.5 - 1.
print(X_train.shape)
X_train = np.expand_dims(X_train, axis=3)
X_train.shape


(60000, 28, 28)
(60000, 28, 28)


(60000, 28, 28, 1)

In [26]:
cframe_trans=cframe.swapaxes(0,1)
# cframe_trans.shape
sub_cframe_trans=cframe_trans[:100,:,:,:]
sub_cframe_trans.shape

(100, 3, 64, 64)

In [32]:
from keras.models import Sequential
from keras.layers.convolutional import Conv3D
from keras.layers.convolutional_recurrent import ConvLSTM2D
from keras.layers.normalization import BatchNormalization
import numpy as np
import matplotlib.pyplot as plt

data = np.load('mnist_test_seq.npy')

# Define image dimensions and frames to be used for LSTM memory
sequence_length = 15 
image_height = data.shape[2]
image_width = data.shape[3]
print(data.shape)

# swap frames and observations so [obs, frames, height, width, channels]
data = data.swapaxes(0, 1)
print("data",data.shape)

# only select first 100 observations to reduce memory- and compute requirements
sub = data[:100, :, :, :]
# add channel dimension (grayscale)
sub = np.expand_dims(sub, 4)

# normalize to 0, 1
#sub = sub / 255
sub[sub < 128] = 0
sub[sub>= 128] = 1
print("sub",sub.shape)


# Define network

# seq = Sequential()
# seq.add(ConvLSTM2D(filters=64, kernel_size=(1,1),
#                    input_shape=(None, image_height, image_width, 1), #Will need to change channels to 3 for real images
#                    padding='same', return_sequences=True,
#                    activation='relu'))
# seq.add(BatchNormalization())
# seq.add(ConvLSTM2D(filters=64, kernel_size=(2,2),
#                    padding='same', return_sequences=True,
#                    activation='relu'))
# seq.add(BatchNormalization())
# seq.add(ConvLSTM2D(filters=64, kernel_size=(1,1),
#                    padding='same', return_sequences=True,
#                    activation='relu'))
# seq.add(BatchNormalization())
# seq.add(ConvLSTM2D(filters=64, kernel_size=(2,2),
#                    padding='same', return_sequences=True,
#                    activation='relu'))
# seq.add(BatchNormalization())
# seq.add(Conv3D(filters=1, kernel_size=(1,1,1),
#                activation='sigmoid',
#                padding='same', data_format='channels_last'))
# seq.compile(loss='binary_crossentropy', optimizer='adam')


# Add helper function for shifting input and output, so previous frame (X_t-1) is used as input to predict next frame (y_t)

def shift_data(data, n_frames=15):
    X = data[:, 0:n_frames, :, :, :]
    y = data[:, 1:(n_frames+1), :, :, :]
    
    return X, y


# Run script

# prepare X, y
X, y = shift_data(sub, sequence_length)

# fit the model
seq.fit(X, y, batch_size=16, epochs=100, validation_split=0.05)

# select a random observation
test_set = np.expand_dims(X[5, :, :, :, :], 0)


# compare to ground truth and visualize


(20, 10000, 64, 64)
data (10000, 20, 64, 64)
sub (100, 20, 64, 64, 1)


In [ ]:
for i in range(0, 13):
    # create plot
    fig = plt.figure(figsize=(10, 5))

    # truth
    ax = fig.add_subplot(122)
    ax.text(1, -3, ('ground truth at time :' + str(i)), fontsize=20, color='b')
    toplot_true = test_set[0, i, ::, ::, 0]
    plt.imshow(toplot_true)
    # predictions
    ax = fig.add_subplot(121)
    ax.text(1, -3, ('predicted frame at time :' + str(i)), fontsize=20, color='b')
    toplot_pred = prediction[0, i+1, ::, ::, 0]

    plt.imshow(toplot_pred)
    plt.savefig(path + '/%i_image.png' % (i + 1))

In [43]:
a = np.array([[1,2,3],[3,4,5],[4,5,6],[1,2,3],[3,4,5],[4,5,6],[1,2,3],[3,4,5],[4,5,6],[1,2,3],[3,4,5],[4,5,6],[1,2,3],[3,4,5],[4,5,6],[1,2,3],[3,4,5],[4,5,6]])

b=a[0:3]
c=a[3:6]
d = a[6:9]
e = a[9:12]
f = a[12:15]
g = a[15:18]
B=np.concatenate((b,c))
b,c,d,e,f,a.shape, B, B.shape

(array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 (18, 3),
 array([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6],
        [1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]),
 (6, 3))

In [21]:
from keras.datasets import mnist
from keras.layers import Input, Dense, Reshape, Flatten, Dropout
from keras.layers import BatchNormalization, Activation, ZeroPadding2D
from keras.layers.advanced_activations import LeakyReLU
from keras.layers.convolutional import UpSampling2D, Conv2D
from keras.models import Sequential, Model
from keras.optimizers import Adam


import matplotlib.pyplot as plt

import sys

import numpy as np


(X_train, _), (_, _) = mnist.load_data()
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)

x_train shape: (25000, 500)
x_test shape: (25000, 500)
